name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mqtt-device

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    - name: List packages
      run: |
        echo "## Installed Packages " >> $GITHUB_STEP_SUMMARY
        echo " " >> $GITHUB_STEP_SUMMARY
        dotnet list package >> $GITHUB_STEP_SUMMARY
